// <auto-generated />
using System;
using MTGCapstone.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTGCapstone.API.Migrations
{
    [DbContext(typeof(CapstoneDbContext))]
    [Migration("20230504184159_changingBoardsQuantityOnDeckCards")]
    partial class changingBoardsQuantityOnDeckCards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.BulkData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompressedSize")
                        .HasColumnType("int");

                    b.Property<string>("ContentEncoding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownloadUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BulkData");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Booster")
                        .HasColumnType("bit");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardBackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardmarketId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cmc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CollectorNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Digital")
                        .HasColumnType("bit");

                    b.Property<int>("EdhrecRank")
                        .HasColumnType("int");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Foil")
                        .HasColumnType("bit");

                    b.Property<string>("Frame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FullArt")
                        .HasColumnType("bit");

                    b.Property<bool>("HighresImage")
                        .HasColumnType("bit");

                    b.Property<string>("IllustrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MtgoFoilId")
                        .HasColumnType("int");

                    b.Property<int>("MtgoId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Nonfoil")
                        .HasColumnType("bit");

                    b.Property<string>("OracleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OracleText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oversized")
                        .HasColumnType("bit");

                    b.Property<int>("PennyRank")
                        .HasColumnType("int");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintsSearchUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Promo")
                        .HasColumnType("bit");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleasedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reprint")
                        .HasColumnType("bit");

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.Property<string>("RulingsUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallSetUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetSearchUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StorySpotlight")
                        .HasColumnType("bit");

                    b.Property<int>("TcgplayerId")
                        .HasColumnType("int");

                    b.Property<bool>("Textless")
                        .HasColumnType("bit");

                    b.Property<string>("Toughness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Variation")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardColorIdentityLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("ColorIdentityLookUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ColorIdentityLookUpId");

                    b.ToTable("CardColorIdentityLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardColorIndicatorLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CardFaceId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("ColorIndicatorLookUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardFaceId");

                    b.HasIndex("CardId");

                    b.HasIndex("ColorIndicatorLookUpId");

                    b.ToTable("CardColorIndicatorLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardColorsLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CardFaceId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("ColorsLookUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardFaceId");

                    b.HasIndex("CardId");

                    b.HasIndex("ColorsLookUpId");

                    b.ToTable("CardColorsLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardFace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("FlavorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IllustrationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OracleText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallArtistId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toughness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeLine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardFaces");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardFinishesLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("FinishesLookUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("FinishesLookUpId");

                    b.ToTable("CardFinishesLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardGamesLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("GamesLookUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("GamesLookUpId");

                    b.ToTable("CardGamesLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardKeywordsLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("KeywordsLookUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("KeywordsLookUpId");

                    b.ToTable("CardKeywordsLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardScryfallArtistIdsLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("ScryfallArtistIdsLookUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ScryfallArtistIdsLookUpId");

                    b.ToTable("CardScryfallArtistIdsLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ColorIdentityLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ColorIdentityLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ColorIndicatorLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ColorIndicatorLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ColorsLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ColorsLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.DeckCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Board")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.DeckCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("DeckCategories");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.DeckCategoryDeckCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DeckCardId")
                        .HasColumnType("int");

                    b.Property<int?>("DeckCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckCardId");

                    b.HasIndex("DeckCategoryId");

                    b.ToTable("DeckCategoryDeckCards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.FinishesLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinishesLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.FormatLegalities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alchemy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brawl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Commander")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explorer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Future")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gladiator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Historic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Historicbrawl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oldschool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pauper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paupercommander")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pioneer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Premodern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Standard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vintage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("FormatLegalities");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.GamesLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GamesLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ImageUris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArtCrop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderCrop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CardFaceId")
                        .HasColumnType("int");

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Large")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Normal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Png")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Small")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardFaceId")
                        .IsUnique()
                        .HasFilter("[CardFaceId] IS NOT NULL");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasFilter("[CardId] IS NOT NULL");

                    b.ToTable("ImageUris");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.KeywordsLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KeywordsLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.MultiverseIdsLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("MultiverseIdsLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Packet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Packets");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.PacketCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("PacketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PacketId");

                    b.ToTable("PacketCards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.PreferredMarketLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreferredMarketLookups");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.PreferredPriceUnitLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PreferredPriceUnitLookups");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Prices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Eur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EurFoil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tix")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Usd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UsdEtched")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UsdFoil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.PurchaseUris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Cardhoarder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cardmarket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tcgplayer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("PurchaseUris");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.RelatedUris", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("Edhrec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gatherer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgplayerInfiniteArticles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcgplayerInfiniteDecks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("RelatedUris");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Ruling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OracleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rulings");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ScryfallArtistIdsLookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScryfallArtistIdsLookUps");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("PreferredMarketLookupId")
                        .HasColumnType("int");

                    b.Property<int?>("PreferredPriceUnitLookupId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PreferredMarketLookupId");

                    b.HasIndex("PreferredPriceUnitLookupId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Tokens.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGCapstone.API.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardColorIdentityLookUp", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany("ColorIdentity")
                        .HasForeignKey("CardId");

                    b.HasOne("MTGCapstone.API.Data.Models.ColorIdentityLookUp", "ColorIdentityLookUp")
                        .WithMany("Cards")
                        .HasForeignKey("ColorIdentityLookUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("ColorIdentityLookUp");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardColorIndicatorLookUp", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.CardFace", "CardFace")
                        .WithMany("ColorIndicator")
                        .HasForeignKey("CardFaceId");

                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany("ColorIndicator")
                        .HasForeignKey("CardId");

                    b.HasOne("MTGCapstone.API.Data.Models.ColorIndicatorLookUp", "ColorIndicatorLookUp")
                        .WithMany("Cards")
                        .HasForeignKey("ColorIndicatorLookUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("CardFace");

                    b.Navigation("ColorIndicatorLookUp");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardColorsLookUp", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.CardFace", "CardFace")
                        .WithMany("Colors")
                        .HasForeignKey("CardFaceId");

                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany("Colors")
                        .HasForeignKey("CardId");

                    b.HasOne("MTGCapstone.API.Data.Models.ColorsLookUp", "ColorsLookUp")
                        .WithMany("Cards")
                        .HasForeignKey("ColorsLookUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("CardFace");

                    b.Navigation("ColorsLookUp");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardFace", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", null)
                        .WithMany("CardFaces")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardFinishesLookUp", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany("Finishes")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGCapstone.API.Data.Models.FinishesLookUp", "FinishesLookUp")
                        .WithMany("Cards")
                        .HasForeignKey("FinishesLookUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("FinishesLookUp");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardGamesLookUp", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany("Games")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGCapstone.API.Data.Models.GamesLookUp", "GamesLookUp")
                        .WithMany("Cards")
                        .HasForeignKey("GamesLookUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("GamesLookUp");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardKeywordsLookUp", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany("Keywords")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGCapstone.API.Data.Models.KeywordsLookUp", "KeywordsLookUp")
                        .WithMany("Cards")
                        .HasForeignKey("KeywordsLookUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("KeywordsLookUp");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardScryfallArtistIdsLookUp", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany("ScryfallArtistIds")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MTGCapstone.API.Data.Models.ScryfallArtistIdsLookUp", "ScryfallArtistIdsLookUp")
                        .WithMany("Cards")
                        .HasForeignKey("ScryfallArtistIdsLookUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("ScryfallArtistIdsLookUp");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Category", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Comment", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Deck", "Deck")
                        .WithMany("Comments")
                        .HasForeignKey("DeckId");

                    b.HasOne("MTGCapstone.API.Data.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("MTGCapstone.API.Data.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Deck", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.DeckCard", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("MTGCapstone.API.Data.Models.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId");

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.DeckCategory", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Deck", "Deck")
                        .WithMany("DeckCategories")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.DeckCategoryDeckCard", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.DeckCard", "DeckCard")
                        .WithMany("DeckCategories")
                        .HasForeignKey("DeckCardId");

                    b.HasOne("MTGCapstone.API.Data.Models.DeckCategory", "DeckCategory")
                        .WithMany("DeckCategoryDeckCards")
                        .HasForeignKey("DeckCategoryId");

                    b.Navigation("DeckCard");

                    b.Navigation("DeckCategory");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.FormatLegalities", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", null)
                        .WithOne("Legalities")
                        .HasForeignKey("MTGCapstone.API.Data.Models.FormatLegalities", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ImageUris", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.CardFace", null)
                        .WithOne("ImageUris")
                        .HasForeignKey("MTGCapstone.API.Data.Models.ImageUris", "CardFaceId");

                    b.HasOne("MTGCapstone.API.Data.Models.Card", null)
                        .WithOne("ImageUris")
                        .HasForeignKey("MTGCapstone.API.Data.Models.ImageUris", "CardId");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Like", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Deck", "Deck")
                        .WithMany("Likes")
                        .HasForeignKey("DeckId");

                    b.HasOne("MTGCapstone.API.Data.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.MultiverseIdsLookUp", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany("MultiverseIds")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Packet", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.User", null)
                        .WithMany("Packets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.PacketCard", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("MTGCapstone.API.Data.Models.Packet", "Packet")
                        .WithMany("Cards")
                        .HasForeignKey("PacketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Packet");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Prices", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", null)
                        .WithOne("Prices")
                        .HasForeignKey("MTGCapstone.API.Data.Models.Prices", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.PurchaseUris", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", null)
                        .WithOne("PurchaseUris")
                        .HasForeignKey("MTGCapstone.API.Data.Models.PurchaseUris", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.RelatedUris", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.Card", null)
                        .WithOne("RelatedUris")
                        .HasForeignKey("MTGCapstone.API.Data.Models.RelatedUris", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.User", b =>
                {
                    b.HasOne("MTGCapstone.API.Data.Models.PreferredMarketLookup", "PreferredMarketLookup")
                        .WithMany("Users")
                        .HasForeignKey("PreferredMarketLookupId");

                    b.HasOne("MTGCapstone.API.Data.Models.PreferredPriceUnitLookup", "PreferredPriceUnitLookup")
                        .WithMany("Users")
                        .HasForeignKey("PreferredPriceUnitLookupId");

                    b.Navigation("PreferredMarketLookup");

                    b.Navigation("PreferredPriceUnitLookup");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Card", b =>
                {
                    b.Navigation("CardFaces");

                    b.Navigation("ColorIdentity");

                    b.Navigation("ColorIndicator");

                    b.Navigation("Colors");

                    b.Navigation("Finishes");

                    b.Navigation("Games");

                    b.Navigation("ImageUris");

                    b.Navigation("Keywords");

                    b.Navigation("Legalities");

                    b.Navigation("MultiverseIds");

                    b.Navigation("Prices");

                    b.Navigation("PurchaseUris");

                    b.Navigation("RelatedUris");

                    b.Navigation("ScryfallArtistIds");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.CardFace", b =>
                {
                    b.Navigation("ColorIndicator");

                    b.Navigation("Colors");

                    b.Navigation("ImageUris");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ColorIdentityLookUp", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ColorIndicatorLookUp", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ColorsLookUp", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Deck", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DeckCards");

                    b.Navigation("DeckCategories");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.DeckCard", b =>
                {
                    b.Navigation("DeckCategories");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.DeckCategory", b =>
                {
                    b.Navigation("DeckCategoryDeckCards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.FinishesLookUp", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.GamesLookUp", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.KeywordsLookUp", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.Packet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.PreferredMarketLookup", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.PreferredPriceUnitLookup", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.ScryfallArtistIdsLookUp", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("MTGCapstone.API.Data.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Comments");

                    b.Navigation("Decks");

                    b.Navigation("Likes");

                    b.Navigation("Packets");
                });
#pragma warning restore 612, 618
        }
    }
}
